# Copyright (c) 2026 James Walmsley <james@fullfat-fs.co.uk>
# SPDX-License-Identifier: Apache-2.0

CONFIG_OTP=y
CONFIG_OTP_PROGRAM=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_PRINTK=y
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
